### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by sqbing** [MikeChongCan/V2EX-iOS-ObjC#10]
一直提示用户名或者密码错误。
我用同样的信息可以登陆网页版。

**Comment by MikeChongCan** [comment]
请问您用的是邮箱地址登录吗？

**Comment by sqbing** [comment]
是的，邮箱地址。
iPhone 5 iOS 7.1.1

**Comment by MikeChongCan** [comment]
尝试用户名登录，记得当时好像是没支持邮箱登录。

**Comment by sqbing** [comment]
测试了用户名登陆，一样现象。
另外，邮箱登陆应该是可以的，我测试用ASI登陆就成功了，AF没用过，不清楚哪里出了问题。

**Comment by MikeChongCan** [comment]
好奇怪，我测试了几个账号都没有出现问题。能否提供一下账号？

**Comment by sqbing** [comment]
可以，给我你的邮箱。

**Comment by MikeChongCan** [comment]
i@wildcat.name
您注册个长得差不多的同样不能登录账号就可以了，不用发您的账号
