### ISSUE TITLE
There are always a "request time out" error in LatestTopicController

### ISSUE THREAD

**Issue by MikeChongCan** [MikeChongCan/V2EX-iOS-ObjC#3]
Most of the API request for normal HTML and parse it with a mobile user agent.
But LatestTopicController loads data using V2EX JSON API( https://github.com/imWildCat/V2EX-iOS/blob/401689eff12445f3f794b268f9eb1e1ab4e946a8/V2EX/Models/V2EXNormalModel.m ), according to https://www.v2ex.com/t/85402.

**Comment by soulgain** [comment]
It seems not answer the question.
After debuging, I think problems here. This JSON API has some undefined behavior. 
The JSON API may return the improper header field value, 

```
"Content-Type" = "text/html; charset=UTF-8"
```

That should be (application/json).
Just few times, that api is right, return (application/json).
At the same time, the AFNetworking do the MIMEType checking when do the base response serialization in AFURLResponseSerialization.

**Comment by MikeChongCan** [comment]
@soulgain , thanks for your respond. And I would fix this problem if I have time.
https://www.v2ex.com/t/110726
