### ISSUE TITLE
希望能统一下已知的api

### ISSUE THREAD

**Issue by kyze8439690** [MikeChongCan/V2EX-iOS-ObjC#6]
你好，我做了android版，希望能共享下您已知的api，我总结了写在我的repo的wiki里面，现有pb3的api不开源完全未知，只能靠pb2的api.py去使用

**Comment by MikeChongCan** [comment]
您好，关于API，我的了解仅限于https://www.v2ex.com/t/85402

目前大多数操作都是解析HTML
